name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          cd hasura
          hasura migrate apply
          hasura metadata apply
